gottscj/Hangfire.Mongo

src/Hangfire.Mongo/MongoStorage.cs
Just for display in the dashboard
=> Obscuring username and password in connection string and adding prefix

src/Hangfire.Mongo/MongoMonitoringApi.cs
Reverts sergeyzwezdin/Hangfire.Mongo#14
=> Revert "Moving index assignment after filtering to ensure proper paging"

nuspecs/HangFire.Mongo.nuspec, src/Hangfire.Mongo.Sample/Hangfire.Mongo.Sample.csproj, src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs, src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs, src/Hangfire.Mongo/Dto/DistributedLockDto.cs
Also made it thread safe so a lock can be acquired multiple times from the same thread.
Updated/added unit tests accordingly.
=> Updated MongoDistributedLock to use atomic operations

src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs, src/Hangfire.Mongo/Dto/DistributedLockDto.cs
- When running on one inatance, the lock is more reponsive due to implementing event wait handler.
- On multi instance installations, distributed lock now supports different lock lifetimes.
=> Improved distributed lock better for both local and distributed installations

src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/MongoUtils/MongoExtensions.cs
=> Create index for jobid on state, jobParameter, jobQueue

src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo/Dto/JobDetailedDto.cs, src/Hangfire.Mongo/Dto/StateDto.cs, src/Hangfire.Mongo/MongoConnection.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
letting mongo serialize/deserialize this field instead
This should fix issue #51
=> Change from json serialized State data string to Dictionary

src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj, src/Hangfire.Mongo.Tests/StateDtoDataFieldSerializerFacts.cs, src/Hangfire.Mongo.sln, src/Hangfire.Mongo/Dto/StateDto.cs, src/Hangfire.Mongo/Serializers/StateDtoDataFieldSerializer.cs
Also Cleaned sln file for removed files.
=> fix StateDto fails to deserialize json representation of state

src/Hangfire.Mongo.Sample/Properties/AssemblyInfo.cs, src/Hangfire.Mongo.Tests/ExpirationManagerFacts.cs, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo.Tests/Properties/AssemblyInfo.cs, src/Hangfire.Mongo/ExpirationManager.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs, src/Hangfire.Mongo/Properties/AssemblyInfo.cs
+ Bump version
+ Update unit tests to add SetDto and HashDto in the same manner as Hangfire does
+  Added Assert to verify values are added when upserting SetDto in "AddRangeToSet"
=> fix(inheritance) - Adds workaround for inheritance upsert issue

src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo/MongoConnection.cs
=> fix(MongoConnection) - Sorts List and Set DTO's by inserted timestamp

src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs
Fixes MonitoringApi.ProcessingJobs returning succeeded jobs
=> fix(monitoring-api) fixes MonitoringApi.ProcessingJobs 

src/Hangfire.Mongo.Sample/App_Start/Startup.Hangfire.cs, src/Hangfire.Mongo.Sample/Hangfire.Mongo.Sample.csproj, src/Hangfire.Mongo.Sample/README.md, src/Hangfire.Mongo.Sample/Web.config
A few tweaks for better out of the box support for Internet Information Server.
Default target is still IIS Express.
=> Better out-of-the-box support for IIS

src/Hangfire.Mongo.Sample/Controllers/HomeController.cs, src/Hangfire.Mongo.Tests/MongoFetchedJobFacts.cs, src/Hangfire.Mongo.Tests/MongoJobQueueFacts.cs, src/Hangfire.Mongo/Dto/JobQueueDto.cs, src/Hangfire.Mongo/MongoFetchedJob.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueue.cs
=> The same job can be enqueued many times

ChangeLog.md, README.md, src/Hangfire.Mongo/Dto/DistributedLockDto.cs, src/Hangfire.Mongo/Dto/HashDto.cs, src/Hangfire.Mongo/Dto/JobDetailedDto.cs, src/Hangfire.Mongo/Dto/JobDto.cs, src/Hangfire.Mongo/Dto/JobQueueDto.cs, src/Hangfire.Mongo/Dto/KeyValueDto.cs, src/Hangfire.Mongo/Dto/ServerDataDto.cs, src/Hangfire.Mongo/Dto/ServerDto.cs, src/Hangfire.Mongo/Dto/SetDto.cs, src/Hangfire.Mongo/Dto/StateDto.cs, src/Hangfire.Mongo/Migration/MongoSchema.cs, src/Hangfire.Mongo/Migration/Steps/Version08/00_PascalCaseRename.cs
Ignore any naming convention and use our own hard coded names.
=> Naming convention

src/Hangfire.Mongo.Tests/MultipleServersFacts.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs, src/Hangfire.Mongo/Signal/Mongo/MongoSignal.cs
Add lock around write only transaction commit
=> Write only transaction lock

README.md, src/Hangfire.Mongo.Sample.ASPNetCore/Startup.cs, src/Hangfire.Mongo.Sample.NETCore/Program.cs, src/Hangfire.Mongo.Sample/App_Start/Startup.Hangfire.cs, src/Hangfire.Mongo.Tests/Utils/ConnectionUtils.cs, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyBase.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyDrop.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyMigrate.cs, src/Hangfire.Mongo/MongoMigrationOptions.cs
It is now possible to backup the entire
database before a migration.
=> Adding backup strategy to migration options

.gitignore
=> Ignore Jetbrains rider folder

.gitignore, src/Hangfire.Mongo.Tests/ExpirationManagerFacts.cs, src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj, src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo.Tests/MongoFetchedJobFacts.cs, src/Hangfire.Mongo.Tests/MongoJobQueueFacts.cs, src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo.Tests/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApiFacts.cs, src/Hangfire.Mongo.sln, src/Hangfire.Mongo/Dto/JobDetailedDto.cs, src/Hangfire.Mongo/Dto/JobDto.cs, src/Hangfire.Mongo/Dto/JobQueueDto.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/Migration/MongoSchemaExtentions.cs, src/Hangfire.Mongo/Migration/Steps/Version09/00_CreateSignalCollection.cs, src/Hangfire.Mongo/Migration/Steps/Version10/00_UpdateSchemaCollection.cs, src/Hangfire.Mongo/Migration/Steps/Version11/00_UseObjectIdForJob.cs, src/Hangfire.Mongo/MongoConnection.cs, src/Hangfire.Mongo/MongoFetchedJob.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/MongoSchema.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs, src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueue.cs, src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApi.cs
+ Use objectId instead of string for Job id
- This will allow sorting by ID
+ Add migration step
=> Sort job state descending

src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs
- Added unit tests
Closes #121
=> fix (monitoring-api)

src/Hangfire.Mongo.Sample/Hangfire.Mongo.Sample.csproj, src/Hangfire.Mongo.Sample/Web.config, src/Hangfire.Mongo.Sample/packages.config, src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
Updated standard sample to .NET v4.6 in order to get on board with the latest own NuGets
=> Update to latest nuget packages

src/Hangfire.Mongo.Tests/Migration/Mongo/MigrationFacts.cs, src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs, src/Hangfire.Mongo.Tests/Utils/CleanDatabaseAttribute.cs, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs, src/Hangfire.Mongo/Dto/BaseJobDto.cs, src/Hangfire.Mongo/Migration/IndexMigration.cs, src/Hangfire.Mongo/Migration/MongoMigrationManager.cs, src/Hangfire.Mongo/Migration/MongoSchemaExtensions.cs, src/Hangfire.Mongo/Migration/Steps/Version05/00_CreateJobIdIndex.cs, src/Hangfire.Mongo/Migration/Steps/Version06/00_StateDataCreateIndex.cs, src/Hangfire.Mongo/Migration/Steps/Version06/01_JobMigration.cs, src/Hangfire.Mongo/Migration/Steps/Version07/00_StateDataRename.cs, src/Hangfire.Mongo/Migration/Steps/Version12/00_CreateIndexes.cs.cs, src/Hangfire.Mongo/Migration/Steps/Version13/01_CreateIndexes.cs, src/Hangfire.Mongo/Migration/Steps/Version13/02_SumCounters.cs, src/Hangfire.Mongo/Migration/Steps/Version14/00_RemoveMergedHashDtos.cs, src/Hangfire.Mongo/Migration/Steps/Version14/01_RemoveLegacyLocks.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyBase.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyDrop.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyMigrate.cs, src/Hangfire.Mongo/MongoSchema.cs, src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApi.cs
- Fixes #156 
- Adds data integrity check for migration tests
- Fixes migration bugs found in data integrity tests
=> Migration fixes (#156)

src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj, src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj, src/Hangfire.Mongo.Sample.NETCore/Program.cs, src/Hangfire.Mongo.Sample/Hangfire.Mongo.Sample.csproj, src/Hangfire.Mongo.Sample/packages.config, src/Hangfire.Mongo.Tests/ConventionPackFacts.cs, src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj, src/Hangfire.Mongo/Dto/BaseJobDto.cs, src/Hangfire.Mongo/Dto/CounterDto.cs, src/Hangfire.Mongo/Dto/DistributedLockDto.cs, src/Hangfire.Mongo/Dto/ExpiringJobDto.cs, src/Hangfire.Mongo/Dto/HashDto.cs, src/Hangfire.Mongo/Dto/JobDto.cs, src/Hangfire.Mongo/Dto/JobQueueDto.cs, src/Hangfire.Mongo/Dto/KeyJobDto.cs, src/Hangfire.Mongo/Dto/ListDto.cs, src/Hangfire.Mongo/Dto/SchemaDto.cs, src/Hangfire.Mongo/Dto/ServerDataDto.cs, src/Hangfire.Mongo/Dto/ServerDto.cs, src/Hangfire.Mongo/Dto/SetDto.cs, src/Hangfire.Mongo/Dto/StateDto.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/JobSummary.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
Update to Hangfire 1.6.21
Update to mongo csharp driver 2.7.2
Added unit test for camelcase convention
Added camelcase convention to netcore sample app
=> Fix camel case (#155)

src/Hangfire.Mongo/Dto/DistributedLockDto.cs, src/Hangfire.Mongo/Dto/ExpiringJobDto.cs, src/Hangfire.Mongo/Dto/JobDto.cs, src/Hangfire.Mongo/Dto/JobQueueDto.cs, src/Hangfire.Mongo/Dto/ServerDataDto.cs, src/Hangfire.Mongo/Dto/ServerDto.cs, src/Hangfire.Mongo/Dto/StateDto.cs
=> Fix timezone issue with conflicting bsonserializer settings

src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj, src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj, src/Hangfire.Mongo.Sample/Web.config, src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/MongoMonitoringApi.cs
Should have been updated to use regex
Also added missing unit test for monitoring-api recurring jobs stats
=> Recurringjob count

src/Hangfire.Mongo.Tests/MongoNotificationObserverErrorFacts.cs, src/Hangfire.Mongo/MongoNotificationObserver.cs
+ Add descriptive error message
=> Dont restart NotificationsObserver if collection is not capped (#204)

ChangeLog.md, src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj, src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj, src/Hangfire.Mongo.Tests/MongoVersionHelperFacts.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyBase.cs, src/Hangfire.Mongo/MongoVersionHelper.cs, src/Hangfire.Mongo/Properties/AssemblyInfo.cs
make getting mongdb version more resilient
=> Create 0.6.5 branch

src/Hangfire.Mongo.Tests/Migration/Mongo/MigrationFacts.cs, src/Hangfire.Mongo.Tests/Migration/Mongo/MongoDatabaseFiller.cs, src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs, src/Hangfire.Mongo.Tests/MongoJobQueueFacts.cs, src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo.Tests/MongoStorageOptionsFacts.cs, src/Hangfire.Mongo.Tests/MongoVersionHelperFacts.cs, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo.Tests/Utils/CleanDatabaseAttribute.cs, src/Hangfire.Mongo.sln.DotSettings, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/MongoJobFetcher.cs, src/Hangfire.Mongo/MongoStorageOptions.cs
Removes Obsolete attribute from "InvisibilityTimeout" in options.
Aligning with Hangfire and making it nullable and only use it if user has set a value
=> InvisibilityTimeout should not be obsolete (yet) #220

src/Hangfire.Mongo/MongoConnection.cs, src/Hangfire.Mongo/MongoJobFetcher.cs
=> create new instance of "MongoJobFetcher" for each thread

src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs, src/Hangfire.Mongo/DistributedLockMutex.cs, src/Hangfire.Mongo/JobQueueSemaphore.cs, src/Hangfire.Mongo/MongoConnection.cs, src/Hangfire.Mongo/MongoFactory.cs, src/Hangfire.Mongo/MongoFetchedJob.cs, src/Hangfire.Mongo/MongoJobFetcher.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/MongoNotificationObserver.cs, src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/MongoStorageOptions.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
Make 
- MongoConnection
- MongoDistributedLock
-DistributedLockMutex  
-JobQueueSemaphore
-MongoFetchedJob 
-MongoJobFetcher
-MongoMonitooringApi
-MongoNotificationObserver
-MongoWriteOnlyTransaction 
public, non-sealed and all public methods virtual.
Added MongoFactory, which is extendable and creates all instances.
=> Make Hangfire.Mongo extendable (#230)

src/Hangfire.Mongo.Tests/Migration/Version17MigrationStepFacts.cs, src/Hangfire.Mongo/Migration/Steps/Version17/01_UpdateIndexes.cs
Index defined for score field in jobGraph collection
=> Index Update in Migration For Score Field In JobGraph Collection

src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/MongoStorageOptions.cs
=> adds bypass migration flag (#256)

src/Hangfire.Mongo/CosmosDB/CosmosBootstrapperConfigurationExtensions.cs, src/Hangfire.Mongo/CosmosDB/CosmosStorage.cs, src/Hangfire.Mongo/Database/HangfireDbContext.cs, src/Hangfire.Mongo/MongoBootstrapperConfigurationExtensions.cs, src/Hangfire.Mongo/MongoFactory.cs, src/Hangfire.Mongo/MongoStorage.cs
=> Replace MongoClient for IMongoClient in constructor and method overloads

src/Hangfire.Mongo/Migration/IndexMigration.cs, src/Hangfire.Mongo/Migration/MigrationLock.cs, src/Hangfire.Mongo/Migration/MongoMigrationException.cs, src/Hangfire.Mongo/Migration/MongoMigrationManager.cs, src/Hangfire.Mongo/Migration/MongoSchemaExtensions.cs
=> makes migration logic public and overridable

ChangeLog.md, src/Hangfire.Mongo.Sample.ASPNetCore/Controllers/HomeController.cs, src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj, src/Hangfire.Mongo.Sample.CosmosDB/Controllers/HomeController.cs, src/Hangfire.Mongo.Sample.CosmosDB/Hangfire.Mongo.Sample.CosmosDB.csproj, src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj, src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo/Dto/JobDto.cs, src/Hangfire.Mongo/Dto/StateDto.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/JobSummary.cs, src/Hangfire.Mongo/MongoConnection.cs, src/Hangfire.Mongo/MongoFetchedJob.cs, src/Hangfire.Mongo/MongoMonitoringApi.cs, src/Hangfire.Mongo/MongoStorage.cs, src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
=> Adds support for Hangfire.Core

ChangeLog.md, src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj, src/Hangfire.Mongo.Sample.CosmosDB/Hangfire.Mongo.Sample.CosmosDB.csproj, src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj, src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj, src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs, src/Hangfire.Mongo/Hangfire.Mongo.csproj, src/Hangfire.Mongo/MongoConnection.cs
- Update to Hangfire.Core 1.8.3
- Update to MongoDB.Driver 2.20.0
- Fix using local server time for server heartbeats #356
=> Update to Hangfire 1.8.3

src/Hangfire.Mongo.Tests/Migration/Mongo/MigrationFacts.cs, src/Hangfire.Mongo.Tests/Migration/Mongo/MongoDatabaseFiller.cs, src/Hangfire.Mongo.Tests/Migration/Mongo/TestMongoMigrationManager.cs, src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs, src/Hangfire.Mongo/Dto/SchemaDto.cs, src/Hangfire.Mongo/Migration/MigrationLock.cs, src/Hangfire.Mongo/Migration/MongoMigrationManager.cs, src/Hangfire.Mongo/Migration/MongoSchemaExtensions.cs, src/Hangfire.Mongo/Migration/Strategies/DropMongoMigrationStrategy.cs, src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategy.cs, src/Hangfire.Mongo/MongoFactory.cs, src/Hangfire.Mongo/MongoMigrationOptions.cs, src/Hangfire.Mongo/MongoStorage.cs
=> Allow migrating down for Drop migration strategy
