gottscj/Hangfire.Mongo

- src/Hangfire.Mongo/MongoMonitoringApi.cs
I had about 50 total jobs and 1 failed. When I went to the Failed page in Dashboard, it said 1 item, but I had to increase the page size to show that 1 job. Swapping the indexing to after the filter by job state fixes the issue.
> Moving index assignment after filtering to ensure proper paging

- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs
- src/Hangfire.Mongo/Helpers/AsyncHelper.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoMonitoringApi.cs
- src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApi.cs
This improves the performance for interaction with the Mongo layer substantially by returning only the minimum data necessary when a request is done.  Primary changes include:
- Switching use of Linq `Skip` and `Take` to use Mongo commands `Skip` and `Limit`;
- Switching use of Linq `Select` to use Mongo commands `Project`;
For cases requiring a JOIN of sorts, I have switched to querying the minimal information on the primary dataset first (in most cases `JobDto` to return the `Id` field), then querying the filter datasets (e.g. `JobQueueDto` or `StateDto`) to do the filtering before then querying the primary dataset for the actual complete objects.  This has the most noticable and largest improvement on the Dashboard, where to get the jobs it was getting the entire dataset in memory and …
> Moving skip, limit and projection to be done Mongo server side

- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo.Tests/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApiFacts.cs
- src/Hangfire.Mongo/PersistentJobQueue/Mongo/MongoJobQueueMonitoringApi.cs
- src/Hangfire.Mongo/Properties/AssemblyInfo.cs
Adding tests for MongoJobQueueMonitoringApi;
Updating MongoJobQueueMonitoringApi to utilize server side limit/skip/projections where possible;
Generally the same as https://github.com/sergeyzwezdin/Hangfire.Mongo/pull/21 -- this just does not include the dll changes, and also includes tests.
> MongoJobQueueMonitoringApi performance improvements and tests

- nuspecs/HangFire.Mongo.nuspec
- src/Hangfire.Mongo.Sample/Hangfire.Mongo.Sample.csproj
- src/Hangfire.Mongo.Sample/Web.config
- src/Hangfire.Mongo.Sample/packages.config
- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo.Tests/packages.config
- src/Hangfire.Mongo/Hangfire.Mongo.csproj
- src/Hangfire.Mongo/MongoUtils/MongoExtensions.cs
- src/Hangfire.Mongo/app.config
- src/Hangfire.Mongo/packages.config
Changes suggested:
Change target framework to .NET 4.5
Update Hangfire.Mongo.nuspec to align to nuget standard folder structure.
Update to latest MongoDB.Driver (2.2.3)
Im not an expert in multiple nuget targets, so i didnt add multiple build configurations for the latest frameworks. Im thinking targeting 4.5 should suffice for now.
> Make nuget package more compatible

- src/Hangfire.Mongo/MongoUtils/MongoExtensions.cs
Hangfire.Mongo runs the isMaster Command on MongoDB, to get the local time from the database.
Depeding on the result, this may cause a FormatException in the MongoDb.Driver.
Response that works:
```
{
"ismaster" : true,
"maxBsonObjectSize" : 16777216,
"maxMessageSizeBytes" : 48000000,
"maxWriteBatchSize" : 1000,
"localTime" : ISODate("2016-02-19T13:03:25.244Z"),
"maxWireVersion" : 4,
"minWireVersion" : 0,
"ok" : 1
}
```
Response that causes FormatException:
```
{
"hosts" : [
"ob1.fus.cated:27017",
"ob2.fus.cated:27017"
],
"setName" : "replicaset1",
"setVersion" : 2,
"ismaster" : true,
"secondary" : false,
"primary" : "ob1.fus.cated:27017",
"me" : "ob1.fus.cated:27017",
"electionId" : ObjectId("56c45d823d4404a3b330555d"),
"maxBsonObjectSize" : 16777216,
"maxMessageSizeBytes" : 48000000, …
```
> Fix FormatException Issue

- nuspecs/HangFire.Mongo.nuspec
The casing of the ID of the HangFire.Core dependency is off in the nuspec file, which causes this error in .NET Core RC2 (targeting full .NET platform): http://www.screencast.com/t/RGcD05w5N0
> Correcting casing in Hangfire.Mongo.nuspec

- src/Hangfire.Mongo.Tests/ExpirationManagerFacts.cs
- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs
- src/Hangfire.Mongo.Tests/MultipleServersFacts.cs
- src/Hangfire.Mongo/Database/HangfireDbContext.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
We can avoid the lock if we model our dto's better.
- This will be done when we have a migration strategy in place.
+ Added index to "Key" field for KeyValueDto
> fix(MongoConnection) - locks for MongoWriteOnlyTransaction.Commit

- src/Hangfire.Mongo/MongoMonitoringApi.cs
Hi @MarLoe,
This PR should fix issue #104 
The aggregation using `{"StateName":{"$ne": null}}` was actually scanning the whole job collection but I've noticed that the function `getCountIfExists` which is the place where we use the dictionary returned from the aggregation was only being used by these statuses: 
```
stats.Enqueued = getCountIfExists(EnqueuedState.StateName);
stats.Failed = getCountIfExists(FailedState.StateName);
stats.Processing = getCountIfExists(ProcessingState.StateName);
stats.Scheduled = getCountIfExists(ScheduledState.StateName);
```
So, to optimize the aggregation, I've added these statuses in the match filter as suggested by @mathieukempe 
Cheers,
Carlos
> Changed job stats aggregation filter

- src/Hangfire.Mongo.Tests/MongoConventionsFacts.cs
- src/Hangfire.Mongo.Tests/Utils/CleanDatabaseAttribute.cs
- src/Hangfire.Mongo.Tests/Utils/ConnectionUtils.cs
- src/Hangfire.Mongo/Dto/DistributedLockDto.cs
- src/Hangfire.Mongo/Dto/HashDto.cs
- src/Hangfire.Mongo/Dto/JobDetailedDto.cs
- src/Hangfire.Mongo/Dto/JobDto.cs
- src/Hangfire.Mongo/Dto/JobQueueDto.cs
- src/Hangfire.Mongo/Dto/KeyValueDto.cs
- src/Hangfire.Mongo/Dto/ListDto.cs
- src/Hangfire.Mongo/Dto/SchemaDto.cs
- src/Hangfire.Mongo/Dto/ServerDataDto.cs
- src/Hangfire.Mongo/Dto/ServerDto.cs
- src/Hangfire.Mongo/Dto/SetDto.cs
- src/Hangfire.Mongo/Dto/StateDto.cs
- src/Hangfire.Mongo/MongoStorage.cs
Avoid any globally registered conventions from ConventionRegistry by
explicitly registering class maps for all DTO types and avoiding the
use of AutoMap().
Apply only the standard conventions by running the default convention
packs on the class maps.
Inspiration and hard work comes from PR #111. Thanks to @janmagnet
> Apply default MongoDB conventions to DTOs

- src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyBase.cs
When backing up collections (before migration), we execute some
native commands directly on the MongoDB. Some of them are
version dependant. So now we check the MongoDB version before
execution.
> (#112) Add version check when backing up collections

- src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs
- src/Hangfire.Mongo/MongoMonitoringApi.cs
- src/Hangfire.Mongo/MongoSchema.cs
- src/Hangfire.Mongo/StateHandlers/DeletedStateHandler.cs
- src/Hangfire.Mongo/StateHandlers/FailedStateHandler.cs
- src/Hangfire.Mongo/StateHandlers/ProcessingStateHandler.cs
- src/Hangfire.Mongo/StateHandlers/State.cs
- src/Hangfire.Mongo/StateHandlers/SucceededStateHandler.cs
I needed some constants for those states. So I went with those provided by Hangfire.
Why didn't we do this sooner? What is the catch? Shouldn't we be doing it?
> Change state names to use those from Hangfire

- src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs
As we target observing capped collections for locks, I think its ok to remove this, until the other functionality is ready
> #139 fix(distributed lock) - Removing EventHandle optimization

- src/Hangfire.Mongo/MongoConnection.cs
This solves the symptoms and the throwing of errors.
We need a better model for the job data which is in progress.
> Dirty fix for duplicate key exception when getting job hash data

- src/Hangfire.Mongo/MongoStorage.cs
Marking access obsolete so users have a chance to speak up if access is needed
> Obsolete public access to DbContext

- ChangeLog.md
- src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj
- src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj
- src/Hangfire.Mongo.Sample/Properties/AssemblyInfo.cs
- src/Hangfire.Mongo.Tests/Properties/AssemblyInfo.cs
- src/Hangfire.Mongo/Hangfire.Mongo.csproj
- src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyBase.cs
- src/Hangfire.Mongo/Properties/AssemblyInfo.cs
Because the 'buildinfo' command does not require root privileges.
> Use 'buildinfo' command instead of 'serverStatus' to get the server version.

- src/Hangfire.Mongo.Tests/Migration/Mongo/MigrationFacts.cs
- src/Hangfire.Mongo/Migration/Strategies/MongoMigrationStrategyDrop.cs
Fix MongoMigrationStrategyDrop.Migrate calling base.Execute which resulted in an endless recursive loop
> Fix MongoMigrationStrategyDrop

- src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs
- src/Hangfire.Mongo/MongoMonitoringApi.cs
This PR fix requeued job (manual or autoretry) being shown as "aborted" when using multiple hangfire servers (#167).
Unit test added as well.
> Fix requeued job (manual or autoretry) being shown as "aborted" when using multiple hangfire servers (issue #167)

- src/Hangfire.Mongo/MongoNotificationObserver.cs
Added a catch for OperationCanceledException to prevent the raising of an error log message.
We expect the underlying Mongo Core code to throw the exception in order to exit execution when the CancellationToken is requesting cancellation. So with this in mind this particular case wouldn't be an error and (I don't feel) is worth raising any logs for.
> Fix #191: Catch OperationCanceledException to hide error log

- src/Hangfire.Mongo/Dto/BaseJobDto.cs
- src/Hangfire.Mongo/Dto/CounterDto.cs
- src/Hangfire.Mongo/Dto/ExpiringJobDto.cs
- src/Hangfire.Mongo/Dto/HashDto.cs
- src/Hangfire.Mongo/Dto/JobDto.cs
- src/Hangfire.Mongo/Dto/KeyJobDto.cs
- src/Hangfire.Mongo/Dto/ListDto.cs
- src/Hangfire.Mongo/Dto/SetDto.cs
Hello Sergey, Martin, Jonas,
After updating to 0.4.1 (and up to 0.6.2), my team noticed jobs weren't being picked up and I traced it down to a filtering problem from `MongoWriteOnlyTransaction`, because of bad discriminators on `Job*` DTOs. This PR solves the problem with as little modifications and risk as possible, by explicitly setting discriminators to expected values.
**The environment**
The main entities our app works with come from plugins, so Mongo Driver's default conventions and discriminators usually aren't enough to cover our use case. That's why we have our own (scalar) discriminator convention, which uses types' `FullName`s instead of just `Name`s.
**The problem**
Even though Hangfire.Mongo uses the hierarchical convention, the custom one we're using caused `Job*` objects' …
> Explicitly set discriminators because filters rely on them

- src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs
- src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
Hello, this PR fixes an issue when we add a set to a job using a key containing some regex chars.
> fix job set filter - escape regex chars

- src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs
- src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs
This PR fixes case when the application crashed, then immediately restarted - can't acquire a lock, even if it has expired.
> Cleanup expired DistributedLock after each wait iteration

- ChangeLog.md
- README.md
- src/Hangfire.Mongo.Sample.ASPNetCore/Startup.cs
- src/Hangfire.Mongo.Sample.ASPNetCore/appsettings.json
- src/Hangfire.Mongo.Sample/App_Start/Startup.Hangfire.cs
- src/Hangfire.Mongo.Sample/Web.config
- src/Hangfire.Mongo/MongoBootstrapperConfigurationExtensions.cs
I added the `[Obsolete]` attribute on the `UseMongoStorage` methods taking both a connection string and a database name.
> Add support for specifying the database name in the connection string

- src/Hangfire.Mongo/MongoConnection.cs
Implement `JobStorageConnection.GetFirstByLowestScoreFromSet's` batch get version. It can reduce the time that get the recurring jobs id. 
In my case, I have thousands of recurring job, they would triggered same time, but the max delay time of triggered would be ten miniutes. But when i add the implementation of  batch get method. the max delay time was significantly reduce.
You can click [this](https://github.com/HangfireIO/Hangfire/search?q=IsBatchingAvailable&unscoped_q=IsBatchingAvailable) to see why the batch get version can reduce the recurring job triggered delay time
> Implement JobStorageConnection.GetFirstByLowestScoreFromSet's batch get version

- ChangeLog.md
- src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj
- src/Hangfire.Mongo.Sample.ASPNetCore/Startup.cs
- src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj
- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo/Dto/ServerDto.cs
- src/Hangfire.Mongo/Hangfire.Mongo.csproj
- src/Hangfire.Mongo/JobQueueSemaphore.cs
- src/Hangfire.Mongo/MongoConnection.cs
- Update to latest Hangfire.Core (v1.7.19)
- Update to latest Mongo drivers (v2.11.6)
- Simplify semaphore logic and support more than 64 waithandles (#264)
- Fixed issue caused by StringIdStoredAsObjectIdConvention() mongo convention (#267)
> Release v0.7.19

- src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs
- src/Hangfire.Mongo/MongoConnection.cs
As of Hangfire version 1.7.0 the storage [`Heartbeat`](https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/d5b921874ef341c6f56a88a58ab0cc35eca7856e/src/Hangfire.Mongo/MongoConnection.cs#L218) method should throw a `BackgroundServerGoneException` when no servers respond to a heartbeat in order to allow [Hangfire.Server.ServerHeartbeatProcess](https://github.com/HangfireIO/Hangfire/blob/b5fabd9e544bdfcbf4eabfb8bde33ba1e30ac4d1/src/Hangfire.Core/Server/ServerHeartbeatProcess.cs#L65) to automatically restart the failed servers.
This should fix a known [issue](https://github.com/HangfireIO/Hangfire/issues/1123) with servers disappearing, that I've experienced as well using the latest Hangfire.Mongo v0.7.22 
[Example](https://github.com/HangfireIO/Hangfire/blob/b5fabd9e544bdfcbf4eabfb8bde33ba1e …
> Heartbeat method should throw a BackgroundServerGoneException when no servers exist for an update

- src/Hangfire.Mongo/MongoConnectException.cs
- src/Hangfire.Mongo/MongoStorage.cs
I noticed that while I was overriding `ConnectionCheckTimeout` the exception message remained the same, causing confusion.
Added the `ConnectionCheckTimeout` as a parameter in the `MongoConnectException` constructor in order to show the correct value in the error message.
> Fix hardcoded timeout in MongoConnectException message.

- src/Hangfire.Mongo/Dto/SchemaDto.cs
- src/Hangfire.Mongo/MongoSchema.cs
Commit 9f5da1d458935d14309f6576ebaa4d7f916c630f (use manual serialization (#331)) does not properly handle the fact that before manual serialization `hangfire.schema._id` was stored as a string of the corresponding `MongoSchema` enum value.
With an existing `hangfire.schema` collection, the migration would fail with the following error:
```
System.InvalidCastException: Unable to cast object of type 'MongoDB.Bson.BsonString' to type 'MongoDB.Bson.BsonInt32'.
at MongoDB.Bson.BsonValue.get_AsInt32()
at Hangfire.Mongo.Dto.SchemaDto..ctor(BsonDocument doc)
at lambda_method81(Closure , BsonDocument )
at MongoDB.Bson.Serialization.Serializers.ProjectingDeserializer`2.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
at …
```
> Fix SchemaDto deserialization

- src/Hangfire.Mongo/Migration/MigrationLock.cs
The same log is already logged with the proper logging mechanism (which can be configured) 3 lines below.
> Remove debug log written with Console.WriteLine

- src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs
- src/Hangfire.Mongo.Tests/MongoDiscriminatorTests.cs
- src/Hangfire.Mongo.Tests/MongoDistributedLockFacts.cs
- src/Hangfire.Mongo.Tests/MongoJobQueueFacts.cs
- src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs
- src/Hangfire.Mongo/Migration/MongoMigrationManager.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoMonitoringApi.cs
The latest version of MongoDB.Driver (2.19.0) changes the default LINQ provider from V2 to V3 any many queries were incompatible with the new provider before this commit, throwing MongoDB.Driver.Linq.ExpressionNotSupportedException.
Fixes #338
> Make all queries compatible with the LINQ V3 provider of MongoDB.Driver

- src/Hangfire.Mongo.Tests/MongoMonitoringApiFacts.cs
- src/Hangfire.Mongo/MongoMonitoringApi.cs
Instead of using an aggregation pipeline, which needs to scan the whole collection to get the results, use Mongo's "Distinct" command which is super fast.
> Improve performance of MongoMonitoringApi.GetQueues()

- ChangeLog.md
- src/Hangfire.Mongo.Sample.ASPNetCore/Controllers/HomeController.cs
- src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj
- src/Hangfire.Mongo.Sample.ASPNetCore/Views/Home/Index.cshtml
- src/Hangfire.Mongo.Sample.CosmosDB/Hangfire.Mongo.Sample.CosmosDB.csproj
- src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj
- src/Hangfire.Mongo.Tests/MongoWriteOnlyTransactionFacts.cs
- src/Hangfire.Mongo/Hangfire.Mongo.csproj
- src/Hangfire.Mongo/MongoJobUpdates.cs
- src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
fix Dashboard does not show exception for retries (#375) fix Slow operations reported by Atlas (#374)
> optimize trimming list and show retry info in dashboard

- src/Hangfire.Mongo.Sample.ASPNetCore/Controllers/HomeController.cs
- src/Hangfire.Mongo.Sample.ASPNetCore/MyRecurringjob.cs
- src/Hangfire.Mongo.Sample.ASPNetCore/SkipWhenPreviousJobIsRunningAttribute.cs
- src/Hangfire.Mongo.Sample.ASPNetCore/Startup.cs
- src/Hangfire.Mongo.Tests/MongoFetchedJobFacts.cs
- src/Hangfire.Mongo/Database/HangfireDbContext.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoFetchedJob.cs
- src/Hangfire.Mongo/MongoJobFetcher.cs
- src/Hangfire.Mongo/MongoWriteOnlyTransaction.cs
- Set FetchedAt to null only when "AddToQueue" is invoked.
- use server time fallback using "serverStatus" if aggregation does not work (if old mongo version)
> fix fetched jobs should only update its heartbeat if processing

- src/Hangfire.Mongo/Dto/DistributedLockDto.cs
- src/Hangfire.Mongo/Dto/JobDto.cs
- src/Hangfire.Mongo/Dto/KeyJobDto.cs
- src/Hangfire.Mongo/Dto/ListDto.cs
- src/Hangfire.Mongo/Dto/NotificationDto.cs
- src/Hangfire.Mongo/Dto/ServerDto.cs
- src/Hangfire.Mongo/Dto/SetDto.cs
- src/Hangfire.Mongo/Dto/StateDto.cs
- src/Hangfire.Mongo/Migration/Steps/Version20/00_RemoveJobQueueDto.cs
This fixes https://github.com/gottscj/Hangfire.Mongo/issues/394 and generally provides support for deserializing nullable fields that are missing in the database due to `IgnoreIfNullConvention(true)` having been active at the point in time that the data was written.
> Fix deserialization of missing nullable fields

- src/Hangfire.Mongo.Sample.ASPNetCore/Hangfire.Mongo.Sample.ASPNetCore.csproj
- src/Hangfire.Mongo.Sample.CosmosDB/Hangfire.Mongo.Sample.CosmosDB.csproj
- src/Hangfire.Mongo.Sample.NETCore/Hangfire.Mongo.Sample.NETCore.csproj
- src/Hangfire.Mongo.Tests/Hangfire.Mongo.Tests.csproj
- src/Hangfire.Mongo/Hangfire.Mongo.csproj
MongoDB.Driver v2.28.0 has been released:
https://www.mongodb.com/community/forums/t/net-driver-2-28-0-released/289745
It now provides strong-named assemblies. This pull request updates the dependencies.
The fact that Hangfire.Mongo still depends on < 2.28.0, which are not signed, causes me to not be able to update MongoDB.Driver in projects that also use Hangfire.Mongo.
> Update mongodb driver

- src/Hangfire.Mongo.Tests/MongoConnectionFacts.cs
- src/Hangfire.Mongo.Tests/MongoConnectionUtcDateTimeFacts.cs
- src/Hangfire.Mongo/DocumentDB/DocumentDbConnection.cs
- src/Hangfire.Mongo/DocumentDB/DocumentDbStorageOptions.cs
- src/Hangfire.Mongo/MongoConnection.cs
- src/Hangfire.Mongo/MongoMigrationOptions.cs
- src/Hangfire.Mongo/MongoStorageOptions.cs
- src/Hangfire.Mongo/UtcDateTime/AggregationUtcDateTimeStrategy.cs
- src/Hangfire.Mongo/UtcDateTime/IsMasterUtcDateTimeStrategy.cs
- src/Hangfire.Mongo/UtcDateTime/ServerStatusUtcDateTimeStrategy.cs
- src/Hangfire.Mongo/UtcDateTime/UtcDateTimeStrategy.cs
Implement retrieval of UTC time using the 'isMaster' command in MongoConnection to enhance compatibility with AWS DocumentDB.
> Add UTC time support for AWS DocumentDB compatibility
